version: "3.7"

services:

  backend:
    container_name: API
    build:
      dockerfile: Dockerfile
      context: ./packages/backEnd
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    user: 1000:1000
    resources:
      limits:
        cpus: '0.50'
        memory: 50M
    security_opt:
      - no-new-privileges
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: Client
    build:
      dockerfile: Dockerfile
      context: ./packages/frontEnd
    restart: on-failure
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: Nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: Certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email --force-renewal -d your-domain.com

networks:
  app-network:
    driver: bridge
  certbot-data:
    external: true
  certbot-var:
    external: true
