version: "3.7"

services:

  backend:
    container_name: API
    build:
      dockerfile: Dockerfile
      context: ./packages/backEnd
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: WEB
    build:
      dockerfile: Dockerfile
      context: ./packages/frontEnd
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge
