version: "3.7"

services:

  backend:
    container_name: API
    build:
      dockerfile: Dockerfile
      context: ./packages/backEnd
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./packages/frontEnd
    restart: on-failure
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-data:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email --force-renewal -d your-domain.com

networks:
  app-network:
    driver: bridge
  certbot-data:
    external: true
