name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      # Runs a set of commands using the runners shell
      - name: Print git commit data
        run: |
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: ${{ GIT_COMMIT_COMMITTER }}
          branch: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: Automated PR
