name: CI

on:
  push:
    branches-ignore: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Github Data
        run: |
          echo " - ${{ github.event.release.target_commitish }}"
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: ${{ github.event.commits[0].message }}
          label: enhancement
          assignee: masterHAWK99
          body: |
            Please read the PR and leave a comment.
          get_diff: false
          allow_no_diff: true
