on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop/FE#14
          title: ${{ github.event.commits[0].message }}
          label: develop
          old_string: "**Write you description here**"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: false
