name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ github.repository }}'
      - name: Heads
        run: |
          echo " - ${{ github.refs }}"
      - name: Committer
        run: |
          echo " - ${{ event.commits[0].committer.username }}"
      - name: Message
        run: |
          echo " - ${{ event.commits[0].message }}"
      - name: Event
        run: |
          echo " - ${{ event.commits[0] }}"
